#
# JBZoo Toolbox - CI-Report-Converter
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    CI-Report-Converter
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/CI-Report-Converter
#

name: 'Any Report to GitHub Annotations'
description: 'The tool converts different error reports to GitHub Actions (Annotations)'
author: 'Denis Smetannikov <admin@jbzoo.com>'

branding:
  icon: 'check-square'
  color: 'blue'

inputs:
  input-file:
    description: 'File path with the original report format. If not set or empty, then the STDIN is used.'
    required: true
  input-format:
    description: 'Source format. Available options: checkstyle, junit, phpmd-json, phpmnd, pmd-cpd, psalm-json'
    default: checkstyle
    required: true
  output-file:
    description: 'File path with the result report format. If not set or empty, then the STDOUT is used.'
  output-format:
    description: 'Target format. Available options: gitlab-json, github-cli, junit, tc-inspections, tc-tests'
    default: github-cli
    required: true
  suite-name:
    description: 'Set custom name of root group/suite'
    required: true

runs:
  using: 'docker'
  image: 'docker://jbzoo/ci-report-converter'
  args:
    - 'convert'
    - '--input-format'
    - ${{ inputs.input-format }}
    - '--output-format'
    - ${{ inputs.output-format }}
    - '--suite-name'
    - ${{ inputs.suite-name }}
    - '--input-file'
    - ${{ inputs.input-file }}
    - '--output-file'
    - ${{ inputs.output-file }}
    - '-vvv'
