#
# JBZoo Toolbox - CI-Report-Converter
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    CI-Report-Converter
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/CI-Report-Converter
#

name: GitHub Action

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - 'master'
  schedule:
    - cron: '15 */8 * * *'

jobs:
  # Trying to run current version of GH action
  develop:
    name: Develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: JUnit.xml
        uses: ./
        with:
          input-format: junit
          input-file: tests/fixtures/origin/phpunit/junit-nested.xml

      - name: CheckStyle.xml
        uses: ./
        with:
          input-format: checkstyle
          input-file: tests/fixtures/origin/phpcs/codestyle.xml

      - name: PHP Mess Detector
        uses: ./
        with:
          input-format: phpmd-json
          input-file: tests/fixtures/origin/phpmd/json.json

      - name: PHP Magic Numbers Detector
        uses: ./
        with:
          input-format: phpmnd
          input-file: tests/fixtures/origin/phpmnd/phpmnd.xml

      - name: Psalm.json
        uses: ./
        with:
          input-format: psalm-json
          input-file: tests/fixtures/origin/psalm/json.json

      - name: PMD CPD.xml
        uses: ./
        with:
          input-format: pmd-cpd
          input-file: tests/fixtures/origin/phpcpd/pmd-cpd.xml


  # Check compatibility of fixtures with master branch in GH Marketplace
  production:
    name: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: JUnit.xml
        continue-on-error: true
        uses: jbzoo/ci-report-converter@master
        with:
          file: tests/fixtures/origin/phpunit/junit-nested.xml

      - name: CheckStyle.xml
        continue-on-error: true
        uses: jbzoo/ci-report-converter@master
        with:
          format: checkstyle
          file: tests/fixtures/origin/phpcs/codestyle.xml

      - name: PHP Mess Detector
        continue-on-error: true
        uses: jbzoo/ci-report-converter@master
        with:
          format: phpmd-json
          file: tests/fixtures/origin/phpmd/json.json

      - name: PHP Magic Numbers Detector
        continue-on-error: true
        uses: jbzoo/ci-report-converter@master
        with:
          format: phpmnd
          file: tests/fixtures/origin/phpmnd/phpmnd.xml

      - name: Psalm.json
        continue-on-error: true
        uses: jbzoo/ci-report-converter@master
        with:
          format: psalm-json
          file: tests/fixtures/origin/psalm/json.json
