#
# JBZoo Toolbox - CI-Report-Converter
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    CI-Report-Converter
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/CI-Report-Converter
#

name: GitHub Action

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - 'master'

jobs:
  develop:
    name: Develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: JUnit.xml
        continue-on-error: true
        uses: ./
        with:
          file: tests/fixtures/origin/phpunit/junit-nested.xml

      - name: CheckStyle.xml
        continue-on-error: true
        uses: ./
        with:
          format: checkstyle
          file: tests/fixtures/origin/phpcs/codestyle.xml

      - name: PHP Mess Detector
        continue-on-error: true
        uses: ./
        with:
          format: phpmd-json
          file: tests/fixtures/origin/phpmd/json.json

      - name: PHP Magic Numbers Detector
        continue-on-error: true
        uses: ./
        with:
          format: phpmd-json
          file: tests/fixtures/origin/phpmd/json.json

      - name: Psalm.json
        continue-on-error: true
        uses: ./
        with:
          format: psalm-json
          file: tests/fixtures/origin/psalm/json.json


  production:
    name: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: JUnit.xml
        continue-on-error: true
        uses: JBZoo/CI-Report-Converter@v2
        with:
          file: tests/fixtures/origin/phpunit/junit-nested.xml

      - name: CheckStyle.xml
        continue-on-error: true
        uses: jbzoo/ci-report-converter@v2.2
        with:
          format: checkstyle
          file: tests/fixtures/origin/phpcs/codestyle.xml

      - name: PHP Mess Detector
        continue-on-error: true
        uses: jbzoo/ci-report-converter@v2.2.0
        with:
          format: phpmd-json
          file: tests/fixtures/origin/phpmd/json.json

      - name: PHP Magic Numbers Detector
        continue-on-error: true
        uses: jbzoo/ci-report-converter@v2
        with:
          format: phpmd-json
          file: tests/fixtures/origin/phpmd/json.json

      - name: Psalm.json
        continue-on-error: true
        uses: jbzoo/ci-report-converter@v2.2.0
        with:
          format: psalm-json
          file: tests/fixtures/origin/psalm/json.json
