#
# JBZoo Toolbox - CI-Report-Converter
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    CI-Report-Converter
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/CI-Report-Converter
#

name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
    tags:
      - '*'
  schedule:
    - cron: '30 */8 * * *'

env:
  COLUMNS: 120
  TERM_PROGRAM: Hyper

jobs:
  phpunit:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    env:
      JBZOO_COMPOSER_UPDATE_FLAGS: ${{ matrix.composer_flags }}
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
        build-way: ["update"]
        composer_flags: [ "--prefer-lowest", "" ]
        include:
          - php-version: 8.0
            build-way: update
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer

      - name: Build the Project
        run: make ${{ matrix.build-way }} --no-print-directory

      - name: 🧪 PHPUnit Tests
        if: ${{ !(matrix.build-way == 'build' && matrix.php-version == 8.0) }}
        run: make test --no-print-directory

      - name: Uploading coverage to coveralls
        env:
            COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make report-coveralls --no-print-directory

      - name: Codecov Report
        uses: codecov/codecov-action@v1
        continue-on-error: true
        if: ${{ matrix.php-version == 7.4 || matrix.php-version == 8.0 }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: '*.xml'
          directory: ./build/coverage_xml/
          fail_ci_if_error: true


  linters:
    name: Linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Build the Project
        run: make update --no-print-directory

      - name: 👍 Code Quality
        run: make codestyle --no-print-directory


  phar:
    name: Phar
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
        experimental: [ false ]
        build-way: ["build", "update"]
        include:
          - php-version: 8.0
            experimental: true
            build-way: update
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Building Phar binary file
        continue-on-error: ${{ matrix.experimental }}
        run: make ${{ matrix.build-way }} --no-print-directory

      - name: Trying to use the phar file
        continue-on-error: ${{ matrix.experimental }}
        run: ./build/ci-report-converter.phar convert --help


  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 🐳 Building Docker Image
        run: make build-docker

      - name: Trying to use the Docker Image
        run: docker run --rm jbzoo-ci-report-converter convert --help
