#
# JBZoo Toolbox - CI-Report-Converter
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    CI-Report-Converter
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/CI-Report-Converter
#

name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - 'master'
    tags:
      - '*'
  schedule:
    - cron: '30 */8 * * *'

env:
  COLUMNS: 120
  TERM_PROGRAM: Hyper

jobs:
  phpunit:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    env:
      JBZOO_COMPOSER_UPDATE_FLAGS: ${{ matrix.composer_flags }}
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
        experimental: [ false ]
        composer_flags: [ "--prefer-lowest", "" ]
        build-way: ["build", "update"]
        include:
          - php-version: "8.0"
            experimental: true
            build-way: "update"
          - php-version: "8.1"
            experimental: true
            build-way: "update"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer

      - name: Build the Project
        continue-on-error: ${{ matrix.experimental }}
        run: make ${{ matrix.build-way }} --no-print-directory

      - name: 🧪 PHPUnit Tests
        continue-on-error: ${{ matrix.experimental }}
        if: ${{ matrix.build-way == 'build' && matrix.php-version != '8.0' && matrix.php-version != '8.1' }}
        run: make test --no-print-directory

      - name: Codecov Report
        uses: codecov/codecov-action@v1
        if: ${{ matrix.build-way == 'update' && matrix.php-version == '7.4' }}
        continue-on-error: ${{ matrix.experimental }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: '*.xml'
          directory: ./build/coverage_xml/
          fail_ci_if_error: true


  linters:
    name: Linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Build the Project
        run: make update --no-print-directory

      - name: 👍 Code Quality
        run: make codestyle --no-print-directory


  phar:
    name: Phar
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
        experimental: [ false ]
        include:
          - php-version: "8.0"
            experimental: true
          - php-version: "8.1"
            experimental: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Building Phar binary file
        continue-on-error: ${{ matrix.experimental }}
        run: make build --no-print-directory

      - name: Trying to use the phar file
        continue-on-error: ${{ matrix.experimental }}
        run: ./build/ci-report-converter.phar --help


  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 🐳 Building Docker Image
        run: make build-docker

      - name: Trying to use the Docker Image
        run: docker run --rm jbzoo-ci-report-converter --help


  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
     - phpunit
     - linters
     - phar
     - docker
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
