#
# JBZoo Toolbox - CI-Report-Converter
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    CI-Report-Converter
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/CI-Report-Converter
#

name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - 'master'
  schedule:
    - cron: '15 */8 * * *'

env:
  COLUMNS: 120
  TERM_PROGRAM: Hyper

jobs:
  genetal:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    env:
      JBZOO_COMPOSER_UPDATE_FLAGS: ${{ matrix.composer_flags }}
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
        experimental: [ false ]
        composer_flags: [ "--prefer-lowest", "" ]
        build-way: ["build", "update"]
        include:
          - php-version: "8.0"
            experimental: true
          - php-version: "8.1"
            experimental: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer

      - name: Build the Project
        continue-on-error: ${{ matrix.experimental }}
        run: make ${{ matrix.build-way }} --no-print-directory

      - name: 🧪 PHPUnit Tests
        continue-on-error: ${{ matrix.experimental }}
        run: make test --no-print-directory


  linters:
    name: Liters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - name: Build the Project
        run: make update --no-print-directory

      - name: 👍 Code Quality
        run: make codestyle --no-print-directory

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 🐳 Building Docker Image
        run: make build-docker

      - name: Trying to use the Docker Image
        run: |
          echo "::group::Try to run it"
          docker run --rm jbzoo-ci-report-converter
          echo "::endgroup::"
          echo "::group::Show help message"
          docker run --rm jbzoo-ci-report-converter convert --help
          echo "::endgroup::"
