#
# JBZoo Toolbox - CI-Report-Converter
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    CI-Report-Converter
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/CI-Report-Converter
#

name: GitHub Action

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - 'master'

jobs:
  genetal:
    name: Testing GitHub Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout code
        run: |
          ls -la fixtures/origin/phpunit/junit-nested.xml
          ls -la ./fixtures/origin/phpunit/junit-nested.xml

      - name: Test Action Output
        uses: ./
        with:
          file: ./fixtures/origin/phpunit/junit-nested.xml
